/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 223903f2e954b99aaa164930eb5d314f)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "SusGameMcp";
	}
	interface Env {
		SUS_DB: D1Database;
		AI: Ai;
		SUS_AUTH_AUDIENCE: "";
		SUS_AUTH_ISSUER: "https://ultimate-beagle-31.clerk.accounts.dev";
		SUS_AUTH_JWKS_URL: "https://ultimate-beagle-31.clerk.accounts.dev/.well-known/jwks.json";
		SUS_AUTH_REQUIRED: "true";
		SUS_AUTH_RESOURCE: "https://sus.wt-lau.workers.dev";
		SUS_AUTH_SCOPE: "openid profile email";
		SUS_AUTH_USERINFO_URL: "https://ultimate-beagle-31.clerk.accounts.dev/oauth/userinfo";
		EXA_API_KEY: string;
		SusGameMcp: DurableObjectNamespace<import("./src/server").SusGameMcp>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUS_AUTH_AUDIENCE" | "SUS_AUTH_ISSUER" | "SUS_AUTH_JWKS_URL" | "SUS_AUTH_REQUIRED" | "SUS_AUTH_RESOURCE" | "SUS_AUTH_SCOPE" | "SUS_AUTH_USERINFO_URL" | "EXA_API_KEY">> {}
}
